version: "3"
services:
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./:/usr/src/
    command: bash -c "/usr/src/entrypoint.sh"
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "y"
      MSSQL_SA_PASSWORD: "Password!"
