INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('eng', 'English')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('tpi', 'Tok Pisin')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('afb', 'Arabic')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('fra', 'French')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('hin', 'Hindi')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('bdi', 'Bahasa Indonesian')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('ilm', 'Bahasa Melayu - Indonesia & Malaysia')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('cmn', 'Mandarin')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('por', 'Portuguese / Brasileiro - Brazilian')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('rus', 'Russian')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('spa', 'Spanish')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('swa', 'Swahili')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('hau', 'Hausa - Nigeria')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('ibo', 'Igbo - Nigeria')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('bis', 'Bislama - Vanuatu')
INSERT INTO Languages(ISO6393Code, EnglishDisplay) VALUES ('vie', 'Vietnamese')