# make the name of the pipeline relevant and associated with the pull request
name: $[ format('PR {0} (build {1})', variables['System.PullRequest.PullRequestNumber'], counter(format('build{0}', variables['System.PullRequest.PullRequestNumber']), 1)) ]
appendCommitMessageToRunName: true

resources:
    repositories:
        - repository: devops
          type: github
          name: BiblioNexusStudio/devops
          endpoint: BiblioNexusStudio

trigger: none

pool:
    vmImage: ubuntu-latest

variables:
    - group: dev-web
    - group: qa-web
    - group: dev-api
    - group: qa-api
    - group: github-app

stages:
    - stage: build
      jobs:
          - job: lint_test_build
            steps:
                - template: templates/checkout_pr.yml@devops
                - template: templates/install_deps.yml
                - script: dotnet build --no-incremental --configuration Release /p:WarningsAsErrors=true
                  displayName: Build
                - script: dotnet test
                  displayName: Test
                - task: DotNetCoreCLI@2
                  inputs:
                      command: publish
                      arguments: --output Build --configuration Release
                  displayName: Generate build zip
                - publish: Build
                  artifact: Build
                  displayName: Publish artifact

    - stage: prevent_deploy_if_migrations
      dependsOn: [build]
      jobs:
          - job: check_for_migrations
            steps:
                - template: templates/checkout_pr.yml@devops
                - script: |
                      git fetch origin $SYSTEM_PULLREQUEST_TARGETBRANCH
                      DIFF=$(git diff --name-only --diff-filter=AM origin/$SYSTEM_PULLREQUEST_TARGETBRANCH..HEAD -- src/Aquifer.API/Data/Migrations)
                      if [ -n "$DIFF" ]; then
                          echo "Deploy being skipped since migrations were included in this commit."
                          echo "It's unsafe to apply migrations except for on the master branch."
                          exit 1
                      else
                          echo "Ok to deploy"
                      fi
                  displayName: Check for migrations


    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: dev
          CheckoutTemplate: templates/checkout_pr.yml@devops
          DependsOn: [prevent_deploy_if_migrations]
          AzureDevopsEnvName: dev-api
          DeployUrl: $(AzureStaticWebAppsDeployUrlDev)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)

    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: qa
          CheckoutTemplate: templates/checkout_pr.yml@devops
          DependsOn: [prevent_deploy_if_migrations]
          AzureDevopsEnvName: qa-api
          DeployUrl: $(AzureStaticWebAppsDeployUrlQa)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)
