using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Aquifer.Data.Enums;

[JsonConverter(typeof(JsonStringEnumConverterWithEnumMemberSupport<BookCode>))]
public enum BookCode
{
    None = 0,
    [EnumMember(Value = "GEN")] BookGEN = 1,
    [EnumMember(Value = "EXO")] BookEXO = 2,
    [EnumMember(Value = "LEV")] BookLEV = 3,
    [EnumMember(Value = "NUM")] BookNUM = 4,
    [EnumMember(Value = "DEU")] BookDEU = 5,
    [EnumMember(Value = "JOS")] BookJOS = 6,
    [EnumMember(Value = "JDG")] BookJDG = 7,
    [EnumMember(Value = "RUT")] BookRUT = 8,
    [EnumMember(Value = "1SA")] Book1SA = 9,
    [EnumMember(Value = "2SA")] Book2SA = 10,
    [EnumMember(Value = "1KI")] Book1KI = 11,
    [EnumMember(Value = "2KI")] Book2KI = 12,
    [EnumMember(Value = "1CH")] Book1CH = 13,
    [EnumMember(Value = "2CH")] Book2CH = 14,
    [EnumMember(Value = "EZR")] BookEZR = 15,
    [EnumMember(Value = "NEH")] BookNEH = 16,
    [EnumMember(Value = "EST")] BookEST = 17,
    [EnumMember(Value = "JOB")] BookJOB = 18,
    [EnumMember(Value = "PSA")] BookPSA = 19,
    [EnumMember(Value = "PRO")] BookPRO = 20,
    [EnumMember(Value = "ECC")] BookECC = 21,
    [EnumMember(Value = "SNG")] BookSNG = 22,
    [EnumMember(Value = "ISA")] BookISA = 23,
    [EnumMember(Value = "JER")] BookJER = 24,
    [EnumMember(Value = "LAM")] BookLAM = 25,
    [EnumMember(Value = "EZK")] BookEZK = 26,
    [EnumMember(Value = "DAN")] BookDAN = 27,
    [EnumMember(Value = "HOS")] BookHOS = 28,
    [EnumMember(Value = "JOL")] BookJOL = 29,
    [EnumMember(Value = "AMO")] BookAMO = 30,
    [EnumMember(Value = "OBA")] BookOBA = 31,
    [EnumMember(Value = "JON")] BookJON = 32,
    [EnumMember(Value = "MIC")] BookMIC = 33,
    [EnumMember(Value = "NAM")] BookNAM = 34,
    [EnumMember(Value = "HAB")] BookHAB = 35,
    [EnumMember(Value = "ZEP")] BookZEP = 36,
    [EnumMember(Value = "HAG")] BookHAG = 37,
    [EnumMember(Value = "ZEC")] BookZEC = 38,
    [EnumMember(Value = "MAL")] BookMAL = 39,
    [EnumMember(Value = "MAT")] BookMAT = 41,
    [EnumMember(Value = "MRK")] BookMRK = 42,
    [EnumMember(Value = "LUK")] BookLUK = 43,
    [EnumMember(Value = "JHN")] BookJHN = 44,
    [EnumMember(Value = "ACT")] BookACT = 45,
    [EnumMember(Value = "ROM")] BookROM = 46,
    [EnumMember(Value = "1CO")] Book1CO = 47,
    [EnumMember(Value = "2CO")] Book2CO = 48,
    [EnumMember(Value = "GAL")] BookGAL = 49,
    [EnumMember(Value = "EPH")] BookEPH = 50,
    [EnumMember(Value = "PHP")] BookPHP = 51,
    [EnumMember(Value = "COL")] BookCOL = 52,
    [EnumMember(Value = "1TH")] Book1TH = 53,
    [EnumMember(Value = "2TH")] Book2TH = 54,
    [EnumMember(Value = "1TI")] Book1TI = 55,
    [EnumMember(Value = "2TI")] Book2TI = 56,
    [EnumMember(Value = "TIT")] BookTIT = 57,
    [EnumMember(Value = "PHM")] BookPHM = 58,
    [EnumMember(Value = "HEB")] BookHEB = 59,
    [EnumMember(Value = "JAS")] BookJAS = 60,
    [EnumMember(Value = "1PE")] Book1PE = 61,
    [EnumMember(Value = "2PE")] Book2PE = 62,
    [EnumMember(Value = "1JN")] Book1JN = 63,
    [EnumMember(Value = "2JN")] Book2JN = 64,
    [EnumMember(Value = "3JN")] Book3JN = 65,
    [EnumMember(Value = "JUD")] BookJUD = 66,
    [EnumMember(Value = "REV")] BookREV = 67
}
