using System.ComponentModel.DataAnnotations;

namespace Aquifer.Data.Enums;

public enum BookId
{
    [Display(Name = "None")]
    None = 0,
    [Display(Name = "Genesis")]
    BookGEN = 1,
    [Display(Name = "Exodus")]
    BookEXO = 2,
    [Display(Name = "Leviticus")]
    BookLEV = 3,
    [Display(Name = "Numbers")]
    BookNUM = 4,
    [Display(Name = "Deuteronomy")]
    BookDEU = 5,
    [Display(Name = "Joshua")]
    BookJOS = 6,
    [Display(Name = "Judges")]
    BookJDG = 7,
    [Display(Name = "Ruth")]
    BookRUT = 8,
    [Display(Name = "1 Samuel")]
    Book1SA = 9,
    [Display(Name = "2 Samuel")]
    Book2SA = 10,
    [Display(Name = "1 Kings")]
    Book1KI = 11,
    [Display(Name = "2 Kings")]
    Book2KI = 12,
    [Display(Name = "1 Chronicles")]
    Book1CH = 13,
    [Display(Name = "2 Chronicles")]
    Book2CH = 14,
    [Display(Name = "Ezra")]
    BookEZR = 15,
    [Display(Name = "Nehemiah")]
    BookNEH = 16,
    [Display(Name = "Esther")]
    BookEST = 17,
    [Display(Name = "Job")]
    BookJOB = 18,
    [Display(Name = "Psalm")]
    BookPSA = 19,
    [Display(Name = "Proverbs")]
    BookPRO = 20,
    [Display(Name = "Ecclesiastes")]
    BookECC = 21,
    [Display(Name = "Song of Solomon")]
    BookSNG = 22,
    [Display(Name = "Isaiah")]
    BookISA = 23,
    [Display(Name = "Jeremiah")]
    BookJER = 24,
    [Display(Name = "Lamentations")]
    BookLAM = 25,
    [Display(Name = "Ezekiel")]
    BookEZK = 26,
    [Display(Name = "Daniel")]
    BookDAN = 27,
    [Display(Name = "Hosea")]
    BookHOS = 28,
    [Display(Name = "Joel")]
    BookJOL = 29,
    [Display(Name = "Amos")]
    BookAMO = 30,
    [Display(Name = "Obadiah")]
    BookOBA = 31,
    [Display(Name = "Jonah")]
    BookJON = 32,
    [Display(Name = "Micah")]
    BookMIC = 33,
    [Display(Name = "Nahum")]
    BookNAM = 34,
    [Display(Name = "Habakkuk")]
    BookHAB = 35,
    [Display(Name = "Zephaniah")]
    BookZEP = 36,
    [Display(Name = "Haggai")]
    BookHAG = 37,
    [Display(Name = "Zechariah")]
    BookZEC = 38,
    [Display(Name = "Malachi")]
    BookMAL = 39,
    [Display(Name = "Matthew")]
    BookMAT = 41,
    [Display(Name = "Mark")]
    BookMRK = 42,
    [Display(Name = "Luke")]
    BookLUK = 43,
    [Display(Name = "John")]
    BookJHN = 44,
    [Display(Name = "Acts")]
    BookACT = 45,
    [Display(Name = "Romans")]
    BookROM = 46,
    [Display(Name = "1 Corinthians")]
    Book1CO = 47,
    [Display(Name = "2 Corinthians")]
    Book2CO = 48,
    [Display(Name = "Galatians")]
    BookGAL = 49,
    [Display(Name = "Ephesians")]
    BookEPH = 50,
    [Display(Name = "Philippians")]
    BookPHP = 51,
    [Display(Name = "Colossians")]
    BookCOL = 52,
    [Display(Name = "1 Thessalonians")]
    Book1TH = 53,
    [Display(Name = "2 Thessalonians")]
    Book2TH = 54,
    [Display(Name = "1 Timothy")]
    Book1TI = 55,
    [Display(Name = "2 Timothy")]
    Book2TI = 56,
    [Display(Name = "Titus")]
    BookTIT = 57,
    [Display(Name = "Philemon")]
    BookPHM = 58,
    [Display(Name = "Hebrews")]
    BookHEB = 59,
    [Display(Name = "James")]
    BookJAS = 60,
    [Display(Name = "1 Peter")]
    Book1PE = 61,
    [Display(Name = "2 Peter")]
    Book2PE = 62,
    [Display(Name = "1 John")]
    Book1JN = 63,
    [Display(Name = "2 John")]
    Book2JN = 64,
    [Display(Name = "3 John")]
    Book3JN = 65,
    [Display(Name = "Jude")]
    BookJUD = 66,
    [Display(Name = "Revelation")]
    BookREV = 67
}
