name: Create Hotfix or Patch

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'What current deployment do you want to apply the commit to?'
                required: true
                type: choice
                options:
                    - qa-internal
                    - prod-internal
            commit_id:
                description: "Commit SHA from master you'd like to apply"
                required: true

permissions:
    contents: read
    deployments: read

jobs:
    create-hotfix-or-patch:
        runs-on: ubuntu-latest
        steps:
            - uses: BiblioNexusStudio/github-actions/create-hotfix-or-patch@master
              with:
                  environment: ${{ github.event.inputs.environment }}
                  commit_id: ${{ github.event.inputs.commit_id }}
                  app_id: ${{ secrets.BIBLIONEXUS_BOT_APP_ID }}
                  private_key: ${{ secrets.BIBLIONEXUS_BOT_PRIVATE_KEY }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
