name: Post-merge (Jobs)

on:
    push:
        branches:
            - master
        paths:
            - 'src/Aquifer.Common/**'
            - 'src/Aquifer.Data/**'
            - 'src/Aquifer.Jobs/**'
    workflow_dispatch:
        inputs:
            environment:
                description: Environment
                type: environment
                required: true

permissions:
    id-token: write
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.x'
            - name: Make build directory
              run: mkdir ./build
            - name: Build Jobs
              run: |
                cd src/Aquifer.Jobs
                dotnet build --configuration Release --output ../build --runtime win-x64
                cd ..
            - name: Publish artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: build

    deploy_jobs_to_dev_qa:
        if: github.ref == 'refs/heads/master' || github.event.inputs.environment == 'dev-qa-jobs'
        name: Deploy Public API to dev
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: dev-qa-jobs
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: build
                  path: build
            - name: 'Run Azure Functions Action'
              uses: Azure/functions-action@v1
              id: fa
              with:
                  app-name: ${{ env.AZURE_FUNCTION_APP_NAME_DEV_QA }}
                  package: build
                  publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE_DEV_QA }}

    # deploy_jobs_to_prod:
    #     if: github.ref == 'refs/heads/master' || github.event.inputs.environment == 'prod-jobs'
    #     name: Deploy Public API to prod
    #     runs-on: ubuntu-latest
    #     needs: build
    #     environment:
    #         name: prod-jobs
    #     steps:
    #         - name: Checkout source code
    #           uses: actions/checkout@v3
    #           with:
    #               ref: ${{ github.event.pull_request.head.sha }}
    #         - uses: ./.github/actions/deploy-to-env
    #           id: deploy
    #           with:
    #               environment: prod
    #               connection-url: ${{ vars.DB_CONNECTION_URL_PROD }}
    #               web-app-name: ${{ vars.AZURE_WEB_APP_NAME_PUBLIC_PROD }}
    #               resource-group: ${{ vars.AZURE_RESOURCE_GROUP_PROD }}
    #               azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #               azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #               azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
