name: Post-merge (Jobs)

on:
    push:
        branches:
            - master
        paths:
            - 'src/Aquifer.Common/**'
            - 'src/Aquifer.Data/**'
            - 'src/Aquifer.Jobs/**'
    workflow_dispatch:
        inputs:
            environment:
                description: Environment
                type: environment
                required: true

permissions:
    id-token: write
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.x'
            - name: Make build directory
              run: mkdir ./build
            - name: Build Jobs
              run: |
                cd src/Aquifer.Jobs
                dotnet build --configuration Release --output ../../build --runtime win-x64
                cd ../..
            - name: Publish artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: build

    deploy_jobs_to_dev_qa:
        if: github.ref == 'refs/heads/master' || github.event.inputs.environment == 'dev-qa-jobs'
        name: Deploy Jobs to dev/qa
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: dev-qa-jobs
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build
            - name: Deploy Jobs to dev/qa
              uses: Azure/functions-action@v1
              with:
                  app-name: ${{ vars.AZURE_FUNCTION_APP_NAME_DEV_QA }}
                  package: build
                  publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE_DEV_QA }}

    deploy_jobs_to_prod:
        if: github.ref == 'refs/heads/master' || github.event.inputs.environment == 'prod-jobs'
        name: Deploy Jobs to prod
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: prod-jobs
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build
            - name: Deploy Jobs to prod
              uses: Azure/functions-action@v1
              with:
                  app-name: ${{ vars.AZURE_FUNCTION_APP_NAME_PROD }}
                  package: build
                  publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE_PROD }}

